# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: saga-project

# Labels to add to all resources and selectors.
commonLabels:
  owner: EVO
  application: SAGA-Project
  stage: development
  version: ver-0.1
  
# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
#Secrets
#ConfigMaps
- ./configmaps/saga-web-configmap.yaml
- ./configmaps/environment-configmap.yaml
#Stateful sets
#Deployments
- ./deployments/camunda.yaml
- ./deployments/saga-web.yaml
- ./deployments/spcarbookingapi.yaml
- ./deployments/spflightbookingapi.yaml
- ./deployments/sphotelbookingapi.yaml

 