apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-qkgd2
    field.cattle.io/publicEndpoints: '[{"addresses":["172.18.0.3","172.18.0.4","172.18.0.5"],"port":443,"protocol":"HTTPS","serviceName":"saga-project:camunda","ingressName":"saga-project:camunda-ingress","hostname":"camunda.localhost","path":"/camunda","allNodes":false}]'
  name: camunda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-saga-project-camunda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-saga-project-camunda
    spec:
      containers:
      - image: camunda/camunda-bpm-platform:latest
        imagePullPolicy: Always
        name: camunda-container
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30