apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-qkgd2
    field.cattle.io/publicEndpoints: '[{"addresses":["172.18.0.3","172.18.0.4","172.18.0.5"],"port":443,"protocol":"HTTPS","serviceName":"saga-project:saga-web","ingressName":"saga-project:saga-web-ingress","hostname":"saga-project.localhost","path":"/","allNodes":false}]'
  name: saga-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-saga-project-saga-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-saga-project-saga-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: environment-configmap
            optional: false
          prefix: saga-web-configmap
        - configMapRef:
            name: saga-web-configmap
            optional: false
        image: evolynsky/saga:spweb
        imagePullPolicy: Always
        name: saga-web-container
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30