apiVersion: apps/v1
kind: Deployment
metadata:
  name: spcarbookingapi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-saga-project-spcarbookingapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-saga-project-spcarbookingapi
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: environment-configmap
            optional: false
        image: evolynsky/saga:spcarbookingapi
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30